export const services = [
  {
    id: "express-detail",
    number: "01",
    name: "Express Detail",
    tagline: "Impeccable in 4 hours.",
    description: "Hand wash, clay bar decontamination, interior vacuum and wipe-down, glass polish, tire dressing.",
    priceFrom: "$450",
    features: [
      "Two-bucket hand wash",
      "Iron & fallout decontamination",
      "Clay bar treatment",
      "Interior vacuum & wipe",
      "Glass polish inside/out",
      "Tire & trim dressing",
    ],
    duration: "4–5 hours",
  },
  {
    id: "paint-correction",
    number: "02",
    name: "Paint Correction",
    tagline: "Microscopic precision, visible results.",
    description: "Single or multi-stage machine polishing to eliminate swirls, scratches, and oxidation. Paint depth measured before and after.",
    priceFrom: "$1,800",
    features: [
      "Paint depth gauge analysis",
      "Wet sanding (if required)",
      "Multi-stage machine polish",
      "Panel-by-panel documentation",
      "IPA wipe-down & inspection",
      "Gloss enhancement coating",
    ],
    duration: "2–4 days",
  },
  {
    id: "ceramic-coating",
    number: "03",
    name: "Ceramic Coating",
    tagline: "Nine-year protection. Zero compromise.",
    description: "Professional-grade SiO₂ ceramic coating applied in controlled environment. 9H hardness, hydrophobic, UV-stable.",
    priceFrom: "$3,200",
    features: [
      "Full paint correction first",
      "GYEON Mohs+ or IGL Kenzo",
      "Multiple layer application",
      "72-hour cure in climate-controlled bay",
      "Coated glass & wheels",
      "Annual maintenance plan",
    ],
    duration: "3–5 days",
  },
  {
    id: "concours-preparation",
    number: "04",
    name: "Concours Preparation",
    tagline: "Judged to the millimeter.",
    description: "Full engine bay detailing, chassis cleaning, show-prep polish, and documentation for concours d'élégance events.",
    priceFrom: "$6,500",
    features: [
      "Engine bay steam clean & detail",
      "Chassis & undercarriage clean",
      "All exterior trim dressed",
      "Leather conditioning & repair",
      "Concours-spec tire prep",
      "Full photographic documentation",
    ],
    duration: "5–7 days",
  },
];

export const work = [
  {
    slug: "ferrari-488-pista",
    title: "Ferrari 488 Pista",
    year: "2023",
    service: "Paint Correction + Ceramic Coating",
    location: "Beverly Hills",
    color: "Rosso Corsa",
    image: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=85",
    beforeImage: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=85",
    afterImage: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=85",
    body: "The client's 488 Pista arrived with two years of swirl marks from an automated wash service — an unfortunately common story. Under our 10,000-lux inspection lights, the paint revealed a web of micro-scratches across nearly every panel. We began with a three-stage decontamination: iron fallout, clay bar, and a citrus pre-wash. Paint depth measurements confirmed we had enough clearcoat to safely perform a two-stage machine polish. After 38 hours of correction work, the paint registered a gloss reading of 98 GU. We finished with four layers of GYEON Mohs+ ceramic coating, cured under controlled humidity for 72 hours.",
  },
  {
    slug: "porsche-911-gt3-rs",
    title: "Porsche 911 GT3 RS",
    year: "2024",
    service: "Concours Preparation",
    location: "Malibu",
    color: "Chalk",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=85",
    beforeImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=85",
    afterImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=85",
    body: "Chalk is one of the most demanding Porsche colours to work with — a light matte-effect finish that amplifies every imperfection. The owner was entering the Quail Motorsports Gathering and needed the car at concours standard in eleven days. We stripped every wheel, detailed the wheel arches with cotton buds where necessary, steam-cleaned the engine bay to factory-fresh condition, and addressed three stone chips on the front bumper with matched touchup. The GT3 RS took second in class.",
  },
  {
    slug: "mclaren-720s",
    title: "McLaren 720S",
    year: "2024",
    service: "Paint Correction",
    location: "West Hollywood",
    color: "Papaya Spark",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85",
    beforeImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85",
    afterImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85",
    body: "McLaren's carbon tub presents unique challenges — access to door shuts and lower sills requires custom extension arms on the polisher. The 720S came to us after a dealer delivery where the prep team had introduced a haze of light scratches. Two days of single-stage correction with Menzerna 400 followed by a refining pass with 3500 brought the panels to a depth that surprised even the owner when he saw it under our inspection lights.",
  },
  {
    slug: "rolls-royce-cullinan",
    title: "Rolls-Royce Cullinan",
    year: "2023",
    service: "Ceramic Coating",
    location: "Bel Air",
    color: "Midnight Sapphire",
    image: "https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=1200&q=85",
    beforeImage: "https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=1200&q=85",
    afterImage: "https://images.unsplash.com/photo-1563694983011-6f4d90358083?w=1200&q=85",
    body: "At 5,700mm long, the Cullinan is one of the largest canvases we work on. Midnight Sapphire is a deep colour-shift paint that rewards painstaking preparation — any contamination left on the surface before coating will be encapsulated and visible under direct light. We spent a full day on decontamination alone. Five coats of IGL Kenzo were then applied across three days, with the vehicle remaining in our climate-controlled bay throughout. The result is a surface so reflective it acts as a mirror.",
  },
  {
    slug: "lamborghini-huracan-sto",
    title: "Lamborghini Huracán STO",
    year: "2024",
    service: "Express Detail + Paint Inspection",
    location: "Calabasas",
    color: "Giallo Belenus",
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=85",
    beforeImage: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=85",
    afterImage: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=85",
    body: "The STO uses a number of exposed carbon fibre body panels alongside its painted sections. Carbon requires different care — sealant rather than polish, and a light coating layer applied with reduced heat. The owner uses this car for track days at Willow Springs and wanted a maintenance detail that would keep the car looking sharp between events without compromising the aerodynamic surfaces.",
  },
  {
    slug: "aston-martin-dbs",
    title: "Aston Martin DBS",
    year: "2023",
    service: "Paint Correction + Ceramic Coating",
    location: "Santa Monica",
    color: "Zaffre Blue",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=85",
    beforeImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=85",
    afterImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=85",
    body: "The DBS in Zaffre Blue is one of the most photographed cars to pass through our studio — the colour shifts from deep indigo to electric blue depending on the light, and paint correction amplifies this quality dramatically. After a two-stage correction, the reflections in the bodywork became so clean that the car appeared digitally rendered. Three coats of GYEON Mohs+ sealed the result.",
  },
];

export const testimonials = [
  {
    quote: "We've used Aurum for every vehicle in our collection for the past six years. The level of care is unlike anything else in Los Angeles. They treat each car as if it's their own.",
    author: "Jonathan M.",
    location: "Malibu, CA",
    vehicle: "2022 Porsche 911 Turbo S & 2020 Ferrari F8 Tributo",
  },
  {
    quote: "My Cullinan came back looking better than when I collected it from the factory. I didn't think that was possible. The team's knowledge and obsession with detail is extraordinary.",
    author: "Priya R.",
    location: "Bel Air, CA",
    vehicle: "2023 Rolls-Royce Cullinan",
  },
  {
    quote: "I brought my GT3 RS in two weeks before Pebble Beach. It placed second in class. I'm not saying Aurum won the award — but I'm not not saying that either.",
    author: "David K.",
    location: "Montecito, CA",
    vehicle: "2023 Porsche 911 GT3 RS",
  },
];

export const journalEntries = [
  {
    slug: "ceramic-coating-guide",
    title: "Everything You Actually Need to Know About Ceramic Coatings",
    date: "2024-11-15",
    category: "Protection",
    excerpt: "The market is full of spray-on 'ceramic' products sold in petrol stations. Here's how to tell them from the real thing, and why it matters.",
    readTime: "8 min",
  },
  {
    slug: "paint-correction-explained",
    title: "Paint Correction: What It Is, What It Isn't, and When You Need It",
    date: "2024-09-20",
    category: "Correction",
    excerpt: "Swirl marks, buffer trails, water etching — we break down the most common paint defects, what causes them, and how they're removed.",
    readTime: "10 min",
  },
  {
    slug: "washing-your-car-correctly",
    title: "The Two-Bucket Method Isn't Enough. Here's What We Actually Do.",
    date: "2024-07-08",
    category: "Maintenance",
    excerpt: "Most 'safe wash' advice online will still introduce swirl marks. This is our full maintenance wash protocol for paint-corrected and ceramic-coated cars.",
    readTime: "6 min",
  },
];
