// Detail packages — fixed-price tiers, Bronze through Diamond.
export const detailPackages = [
  {
    id: "bronze-refresh",
    number: "01",
    name: "Bronze Refresh",
    tagline: "Perfect for maintenance clients.",
    description: "Our maintenance wash — a careful hand wash, cleaned wheels and tires, and a tidy interior to keep a clean car clean.",
    price: "$175",
    features: [
      "Hand wash",
      "Wheels & tires cleaned",
      "Tire dressing",
      "Door jamb wipe down",
      "Interior vacuum",
      "Dash & console wipe down",
      "Windows cleaned",
      "Air freshener",
    ],
  },
  {
    id: "silver-detail",
    number: "02",
    name: "Silver Detail",
    tagline: "Most popular for daily drivers.",
    description: "A deeper interior clean with carpet and seat shampooing, plus a spray sealant that protects the paint for two to three months.",
    price: "$250",
    features: [
      "Everything in Bronze",
      "Deep interior wipe down",
      "Plastic & vinyl protection",
      "Light stain treatment",
      "Floor mat cleaning",
      "Spray sealant protection (2–3 months)",
      "Carpet & seat shampooing",
    ],
  },
  {
    id: "gold-detail",
    number: "03",
    name: "Gold Detail",
    tagline: "Interior reset package.",
    description: "A full interior reset — leather cleaning and conditioning, detailed brushwork, clay-towel treatment, and enhanced paint gloss.",
    price: "$325",
    features: [
      "Everything in Silver",
      "Leather cleaning & conditioning",
      "Pet hair removal (light)",
      "Crevice cleaning",
      "Detailed interior brush work",
      "Clay towel treatment",
      "Enhanced paint gloss",
    ],
  },
  {
    id: "platinum-detail",
    number: "04",
    name: "Platinum Detail",
    tagline: "Full interior restoration.",
    description: "A full interior restoration with steam cleaning, deep stain removal, engine bay cleaning, and iron-decontaminated, sealed paint.",
    price: "$425",
    features: [
      "Everything in Gold",
      "Steam cleaning",
      "Deep stain removal",
      "Heavy interior detailing",
      "Engine bay cleaning",
      "Iron decontamination treatment",
      "Paint protection sealant",
    ],
  },
  {
    id: "diamond-detail",
    number: "05",
    name: "Diamond Detail",
    tagline: "Complete vehicle transformation.",
    description: "Our complete transformation — multi-step paint decontamination, paint enhancement polish, deep steam treatment, and a premium-protected showroom finish.",
    price: "$550",
    features: [
      "Everything in Platinum",
      "Multi-step paint decontamination",
      "Paint enhancement polish",
      "Heavy pet hair removal",
      "Deep steam treatment",
      "Premium paint protection",
      "Showroom finish",
    ],
  },
];

// Ceramic coating packages — priced from, by durability tier.
export const ceramicPackages = [
  {
    id: "ceramic-1-2-year",
    number: "01",
    name: "1–2 Year Ceramic Coating",
    duration: "1–2 years",
    priceFrom: "$550",
    features: [
      "Exterior prep",
      "Paint decontamination",
      "Ceramic coating application",
    ],
  },
  {
    id: "ceramic-3-4-year",
    number: "02",
    name: "3–4 Year Ceramic Coating",
    duration: "3–4 years",
    priceFrom: "$850",
    features: [
      "Paint decontamination",
      "Light paint enhancement",
      "Ceramic coating installation",
    ],
  },
  {
    id: "ceramic-5-6-year",
    number: "03",
    name: "5–6 Year Ceramic Coating",
    duration: "5–6 years",
    priceFrom: "$1,250",
    features: [
      "Paint correction included",
      "Ceramic coating installation",
      "Enhanced gloss & protection",
    ],
  },
  {
    id: "ceramic-9-year",
    number: "04",
    name: "9 Year Ceramic Coating",
    duration: "9 years",
    priceFrom: "$1,850",
    features: [
      "Multi-stage paint correction",
      "Premium ceramic coating",
      "Maximum durability & gloss",
    ],
  },
];

// À la carte add-on services.
export const addOns = [
  { name: "Headlight Restoration", priceFrom: "$55" },
  { name: "Engine Bay Detail", priceFrom: "$50" },
  { name: "Pet Hair Removal", priceFrom: "$50" },
  { name: "Clay Bar Treatment", priceFrom: "$75" },
  { name: "Iron Decontamination", priceFrom: "$75" },
  { name: "Leather Conditioning", priceFrom: "$50" },
  { name: "Carpet Shampoo Extraction", priceFrom: "$75" },
  { name: "Steam Cleaning", priceFrom: "$100" },
  { name: "Trim Restoration", priceFrom: "$75" },
  { name: "Odor Removal Treatment", priceFrom: "$75" },
  { name: "Water Spot Removal", priceFrom: "$100" },
  { name: "Bug & Tar Removal", priceFrom: "$50" },
  { name: "Seat Extraction", priceFrom: "$100" },
  { name: "Paint Enhancement Polish", priceFrom: "$200" },
  { name: "Scratch Reduction", priceFrom: "$150" },
  { name: "Wheel Ceramic Coating", priceFrom: "$150" },
  { name: "Glass Ceramic Coating", priceFrom: "$100" },
];

export const work = [
  {
    slug: "ferrari-488-pista",
    title: "Ferrari 488 Pista",
    year: "2023",
    service: "Paint Correction + Ceramic Coating",
    location: "Beverly Hills",
    color: "Rosso Corsa",
    image: "/images/IMG_1264.jpg",
    beforeImage: "/images/IMG_1313.jpg",
    afterImage: "/images/IMG_1264.jpg",
    body: "The client's 488 Pista arrived with two years of swirl marks from an automated wash service — an unfortunately common story. Under our 10,000-lux inspection lights, the paint revealed a web of micro-scratches across nearly every panel. We began with a three-stage decontamination: iron fallout, clay bar, and a citrus pre-wash. Paint depth measurements confirmed we had enough clearcoat to safely perform a two-stage machine polish. After 38 hours of correction work, the paint registered a gloss reading of 98 GU. We finished with four layers of GYEON Mohs+ ceramic coating, cured under controlled humidity for 72 hours.",
  },
  {
    slug: "porsche-911-gt3-rs",
    title: "Porsche 911 GT3 RS",
    year: "2024",
    service: "Concours Preparation",
    location: "Malibu",
    color: "Chalk",
    image: "/images/IMG_1071.jpg",
    beforeImage: "/images/IMG_1347.jpg",
    afterImage: "/images/IMG_1071.jpg",
    body: "Chalk is one of the most demanding Porsche colours to work with — a light matte-effect finish that amplifies every imperfection. The owner was entering the Quail Motorsports Gathering and needed the car at concours standard in eleven days. We stripped every wheel, detailed the wheel arches with cotton buds where necessary, steam-cleaned the engine bay to factory-fresh condition, and addressed three stone chips on the front bumper with matched touchup. The GT3 RS took second in class.",
  },
  {
    slug: "mclaren-720s",
    title: "McLaren 720S",
    year: "2024",
    service: "Paint Correction",
    location: "West Hollywood",
    color: "Papaya Spark",
    image: "/images/IMG_9282.jpg",
    beforeImage: "/images/IMG_1042.jpg",
    afterImage: "/images/IMG_9282.jpg",
    body: "McLaren's carbon tub presents unique challenges — access to door shuts and lower sills requires custom extension arms on the polisher. The 720S came to us after a dealer delivery where the prep team had introduced a haze of light scratches. Two days of single-stage correction with Menzerna 400 followed by a refining pass with 3500 brought the panels to a depth that surprised even the owner when he saw it under our inspection lights.",
  },
  {
    slug: "rolls-royce-cullinan",
    title: "Rolls-Royce Cullinan",
    year: "2023",
    service: "Ceramic Coating",
    location: "Bel Air",
    color: "Midnight Sapphire",
    image: "/images/IMG_1347.jpg",
    beforeImage: "/images/IMG_1397.jpg",
    afterImage: "/images/IMG_1347.jpg",
    body: "At 5,700mm long, the Cullinan is one of the largest canvases we work on. Midnight Sapphire is a deep colour-shift paint that rewards painstaking preparation — any contamination left on the surface before coating will be encapsulated and visible under direct light. We spent a full day on decontamination alone. Five coats of IGL Kenzo were then applied across three days, with the vehicle remaining in our climate-controlled bay throughout. The result is a surface so reflective it acts as a mirror.",
  },
  {
    slug: "lamborghini-huracan-sto",
    title: "Lamborghini Huracán STO",
    year: "2024",
    service: "Express Detail + Paint Inspection",
    location: "Calabasas",
    color: "Giallo Belenus",
    image: "/images/IMG_9586.jpg",
    beforeImage: "/images/IMG_1313.jpg",
    afterImage: "/images/IMG_9586.jpg",
    body: "The STO uses a number of exposed carbon fibre body panels alongside its painted sections. Carbon requires different care — sealant rather than polish, and a light coating layer applied with reduced heat. The owner uses this car for track days at Willow Springs and wanted a maintenance detail that would keep the car looking sharp between events without compromising the aerodynamic surfaces.",
  },
  {
    slug: "aston-martin-dbs",
    title: "Aston Martin DBS",
    year: "2023",
    service: "Paint Correction + Ceramic Coating",
    location: "Santa Monica",
    color: "Zaffre Blue",
    image: "/images/IMG_1136.jpg",
    beforeImage: "/images/IMG_0870.jpg",
    afterImage: "/images/IMG_1136.jpg",
    body: "The DBS in Zaffre Blue is one of the most photographed cars to pass through our studio — the colour shifts from deep indigo to electric blue depending on the light, and paint correction amplifies this quality dramatically. After a two-stage correction, the reflections in the bodywork became so clean that the car appeared digitally rendered. Three coats of GYEON Mohs+ sealed the result.",
  },
];

export const testimonials = [
  {
    quote: "We've used Bubbles for every vehicle in our collection for the past six years. The level of care is unlike anything else in the Bay Area. They treat each car as if it's their own.",
    author: "Jonathan M.",
    location: "Malibu, CA",
    vehicle: "2022 Porsche 911 Turbo S & 2020 Ferrari F8 Tributo",
  },
  {
    quote: "My Cullinan came back looking better than when I collected it from the factory. I didn't think that was possible. The team's knowledge and obsession with detail is extraordinary.",
    author: "Priya R.",
    location: "Bel Air, CA",
    vehicle: "2023 Rolls-Royce Cullinan",
  },
  {
    quote: "I brought my GT3 RS in two weeks before Pebble Beach. It placed second in class. I'm not saying Bubbles won the award — but I'm not not saying that either.",
    author: "David K.",
    location: "Montecito, CA",
    vehicle: "2023 Porsche 911 GT3 RS",
  },
];

export const journalEntries = [
  {
    slug: "ceramic-coating-guide",
    title: "Everything You Actually Need to Know About Ceramic Coatings",
    date: "2024-11-15",
    category: "Protection",
    excerpt: "The market is full of spray-on 'ceramic' products sold in petrol stations. Here's how to tell them from the real thing, and why it matters.",
    readTime: "8 min",
  },
  {
    slug: "paint-correction-explained",
    title: "Paint Correction: What It Is, What It Isn't, and When You Need It",
    date: "2024-09-20",
    category: "Correction",
    excerpt: "Swirl marks, buffer trails, water etching — we break down the most common paint defects, what causes them, and how they're removed.",
    readTime: "10 min",
  },
  {
    slug: "washing-your-car-correctly",
    title: "The Two-Bucket Method Isn't Enough. Here's What We Actually Do.",
    date: "2024-07-08",
    category: "Maintenance",
    excerpt: "Most 'safe wash' advice online will still introduce swirl marks. This is our full maintenance wash protocol for paint-corrected and ceramic-coated cars.",
    readTime: "6 min",
  },
];
