// Detail packages — fixed-price tiers, Bronze through Diamond.
export const detailPackages = [
  {
    id: "bronze-refresh",
    number: "01",
    name: "Bronze Refresh",
    tagline: "Perfect for maintenance clients.",
    description: "Our maintenance wash — a careful hand wash, cleaned wheels and tires, and a tidy interior to keep a clean car clean.",
    price: "$175",
    features: [
      "Hand wash",
      "Wheels & tires cleaned",
      "Tire dressing",
      "Door jamb wipe down",
      "Interior vacuum",
      "Dash & console wipe down",
      "Windows cleaned",
      "Air freshener",
    ],
  },
  {
    id: "silver-detail",
    number: "02",
    name: "Silver Detail",
    tagline: "Most popular for daily drivers.",
    description: "A deeper interior clean with carpet and seat shampooing, plus a spray sealant that protects the paint for two to three months.",
    price: "$250",
    features: [
      "Everything in Bronze",
      "Deep interior wipe down",
      "Plastic & vinyl protection",
      "Light stain treatment",
      "Floor mat cleaning",
      "Spray sealant protection (2–3 months)",
      "Carpet & seat shampooing",
    ],
  },
  {
    id: "gold-detail",
    number: "03",
    name: "Gold Detail",
    tagline: "Interior reset package.",
    description: "A full interior reset — leather cleaning and conditioning, detailed brushwork, clay-towel treatment, and enhanced paint gloss.",
    price: "$325",
    features: [
      "Everything in Silver",
      "Leather cleaning & conditioning",
      "Pet hair removal (light)",
      "Crevice cleaning",
      "Detailed interior brush work",
      "Clay towel treatment",
      "Enhanced paint gloss",
    ],
  },
  {
    id: "platinum-detail",
    number: "04",
    name: "Platinum Detail",
    tagline: "Full interior restoration.",
    description: "A full interior restoration with steam cleaning, deep stain removal, engine bay cleaning, and iron-decontaminated, sealed paint.",
    price: "$425",
    features: [
      "Everything in Gold",
      "Steam cleaning",
      "Deep stain removal",
      "Heavy interior detailing",
      "Engine bay cleaning",
      "Iron decontamination treatment",
      "Paint protection sealant",
    ],
  },
  {
    id: "diamond-detail",
    number: "05",
    name: "Diamond Detail",
    tagline: "Complete vehicle transformation.",
    description: "Our complete transformation — multi-step paint decontamination, paint enhancement polish, deep steam treatment, and a premium-protected showroom finish.",
    price: "$550",
    features: [
      "Everything in Platinum",
      "Multi-step paint decontamination",
      "Paint enhancement polish",
      "Heavy pet hair removal",
      "Deep steam treatment",
      "Premium paint protection",
      "Showroom finish",
    ],
  },
];

// Ceramic coating packages — priced from, by durability tier.
export const ceramicPackages = [
  {
    id: "ceramic-1-2-year",
    number: "01",
    name: "1–2 Year Ceramic Coating",
    duration: "1–2 years",
    priceFrom: "$550",
    features: [
      "Exterior prep",
      "Paint decontamination",
      "Ceramic coating application",
    ],
  },
  {
    id: "ceramic-3-4-year",
    number: "02",
    name: "3–4 Year Ceramic Coating",
    duration: "3–4 years",
    priceFrom: "$850",
    features: [
      "Paint decontamination",
      "Light paint enhancement",
      "Ceramic coating installation",
    ],
  },
  {
    id: "ceramic-5-6-year",
    number: "03",
    name: "5–6 Year Ceramic Coating",
    duration: "5–6 years",
    priceFrom: "$1,250",
    features: [
      "Paint correction included",
      "Ceramic coating installation",
      "Enhanced gloss & protection",
    ],
  },
  {
    id: "ceramic-9-year",
    number: "04",
    name: "9 Year Ceramic Coating",
    duration: "9 years",
    priceFrom: "$1,850",
    features: [
      "Multi-stage paint correction",
      "Premium ceramic coating",
      "Maximum durability & gloss",
    ],
  },
];

// À la carte add-on services.
export const addOns = [
  { name: "Headlight Restoration", priceFrom: "$55" },
  { name: "Engine Bay Detail", priceFrom: "$50" },
  { name: "Pet Hair Removal", priceFrom: "$50" },
  { name: "Clay Bar Treatment", priceFrom: "$75" },
  { name: "Iron Decontamination", priceFrom: "$75" },
  { name: "Leather Conditioning", priceFrom: "$50" },
  { name: "Carpet Shampoo Extraction", priceFrom: "$75" },
  { name: "Steam Cleaning", priceFrom: "$100" },
  { name: "Trim Restoration", priceFrom: "$75" },
  { name: "Odor Removal Treatment", priceFrom: "$75" },
  { name: "Water Spot Removal", priceFrom: "$100" },
  { name: "Bug & Tar Removal", priceFrom: "$50" },
  { name: "Seat Extraction", priceFrom: "$100" },
  { name: "Paint Enhancement Polish", priceFrom: "$200" },
  { name: "Scratch Reduction", priceFrom: "$150" },
  { name: "Wheel Ceramic Coating", priceFrom: "$150" },
  { name: "Glass Ceramic Coating", priceFrom: "$100" },
];

// Ongoing maintenance plans — recurring visits, priced per visit.
export const maintenancePackages = [
  {
    id: "weekly-maintenance",
    number: "01",
    name: "Weekly Maintenance",
    price: "$115",
    per: "per visit",
    frequency: "4 visits per month",
  },
  {
    id: "bi-weekly-maintenance",
    number: "02",
    name: "Bi-Weekly Maintenance",
    price: "$150",
    per: "per visit",
    frequency: "2 visits per month",
  },
  {
    id: "monthly-maintenance",
    number: "03",
    name: "Monthly Maintenance",
    price: "$225",
    per: "per visit",
    frequency: "1 visit per month",
  },
  {
    id: "quarterly-maintenance",
    number: "04",
    name: "Quarterly Maintenance",
    price: "$350",
    per: "per visit",
    frequency: "Every 3 months",
  },
];

export const work = [
  {
    slug: "koenigsegg-regera",
    title: "Koenigsegg Regera",
    year: "2023",
    service: "Paint Correction + Ceramic Coating",
    location: "Monterey / Car Week",
    color: "Red",
    image: "/images/IMG_1264.jpg",
    beforeImage: "/images/IMG_1313.jpg",
    afterImage: "/images/IMG_1264.jpg",
    body: "A Koenigsegg Regera is among the rarest cars ever to come through our studio, and its finish demands a correspondingly careful hand. We began with a full multi-stage decontamination, then a paint-correction pass under our 10,000-lux inspection lighting to remove the fine swirling that even the most careful owners accumulate. The deep red came back with the kind of wet, liquid gloss the colour deserves, sealed beneath a premium ceramic coating cured in our climate-controlled bay.",
  },
  {
    slug: "porsche-carrera-gt",
    title: "Porsche Carrera GT",
    year: "2024",
    service: "Paint Correction + Ceramic Coating",
    location: "Monterey / Car Week",
    color: "Purple",
    image: "/images/IMG_1071.jpg",
    beforeImage: "/images/IMG_1347.jpg",
    afterImage: "/images/IMG_1071.jpg",
    body: "The Carrera GT is a true analog icon — an engineering landmark that rewards patient, conservative work over aggressive correction. We treated the paint as the irreplaceable original it is: gentle decontamination, a refined polish to lift its depth without thinning the clearcoat, and a protective ceramic layer to preserve it. The purple came alive under the lights afterward, exactly as it should be — only cleaner, glossier, and protected for years to come.",
  },
  {
    slug: "mclaren-750s",
    title: "McLaren 750S",
    year: "2024",
    service: "Paint Correction",
    location: "Bay Area",
    color: "Black & Blue",
    image: "/images/IMG_9282.jpg",
    beforeImage: "/images/IMG_1042.jpg",
    afterImage: "/images/IMG_9282.jpg",
    body: "McLaren's tight panel gaps and carbon detailing present unique challenges — reaching the door shuts and lower sills safely requires custom extension arms on the polisher. This 750S came in for full paint correction, and we worked panel by panel to remove the haze of fine scratches that accumulates from routine washing. The blue-over-black bodywork read far deeper and cleaner under our inspection lights once the finish was refined and protected.",
  },
  {
    slug: "rolls-royce-cullinan",
    title: "Rolls-Royce Cullinan",
    year: "2023",
    service: "Ceramic Coating",
    location: "Bay Area",
    color: "Midnight Sapphire",
    image: "/images/IMG_1347.jpg",
    beforeImage: "/images/IMG_1397.jpg",
    afterImage: "/images/IMG_1347.jpg",
    body: "At 5,700mm long, the Cullinan is one of the largest canvases we work on. Midnight Sapphire is a deep colour-shift paint that rewards painstaking preparation — any contamination left on the surface before coating will be encapsulated and visible under direct light. We spent a full day on decontamination alone. Five coats of IGL Kenzo were then applied across three days, with the vehicle remaining in our climate-controlled bay throughout. The result is a surface so reflective it acts as a mirror.",
  },
  {
    slug: "lamborghini-huracan-spyder",
    title: "Lamborghini Huracán Spyder",
    year: "2024",
    service: "Paint Correction + Ceramic Coating",
    location: "Bay Area",
    color: "—",
    image: "/images/IMG_9586.jpg",
    beforeImage: "/images/IMG_1313.jpg",
    afterImage: "/images/IMG_9586.jpg",
    body: "With the top stowed, a Spyder puts almost the entire car on display at once — every panel, the engine cover, and the cabin all visible together — so the finish has to read flawlessly from every angle. We carried out a full paint correction and ceramic coating, paying particular attention to the contours around the air intakes and the folding-roof mechanism where contamination likes to hide. The result is a glass-like shine that holds up under direct light.",
  },
  {
    slug: "lamborghini-svj-pagani-utopia",
    title: "Lamborghini Aventador SVJ & Pagani Utopia",
    year: "2023",
    service: "Paint Correction + Ceramic Coating",
    location: "Monterey / Car Week",
    color: "—",
    image: "/images/IMG_1136.jpg",
    beforeImage: "/images/IMG_0870.jpg",
    afterImage: "/images/IMG_1136.jpg",
    body: "A two-car feature for a single collector: a Lamborghini Aventador SVJ and a Pagani Utopia, detailed back to back. The SVJ's aggressive aero and exposed carbon, and the Utopia's hand-finished bodywork, each called for a different touch — but both received the same regimen of full decontamination, paint correction, and premium ceramic protection. Two very different hypercars, finished to one standard.",
  },
];

export const testimonials = [
  {
    quote: "We've used Bubbles for every vehicle in our collection for the past six years. The level of care is unlike anything else in the Bay Area. They treat each car as if it's their own.",
    author: "Jonathan M.",
    location: "Atherton, CA",
    vehicle: "2022 Porsche 911 Turbo S & 2020 Ferrari F8 Tributo",
  },
  {
    quote: "My Cullinan came back looking better than when I collected it from the factory. I didn't think that was possible. The team's knowledge and obsession with detail is extraordinary.",
    author: "Priya R.",
    location: "Hillsborough, CA",
    vehicle: "2023 Rolls-Royce Cullinan",
  },
  {
    quote: "I brought my GT3 RS in two weeks before Pebble Beach. It placed second in class. I'm not saying Bubbles won the award — but I'm not not saying that either.",
    author: "David K.",
    location: "Los Altos Hills, CA",
    vehicle: "2023 Porsche 911 GT3 RS",
  },
];

export const journalEntries = [
  {
    slug: "ceramic-coating-guide",
    title: "Everything You Actually Need to Know About Ceramic Coatings",
    date: "2024-11-15",
    category: "Protection",
    excerpt: "The market is full of spray-on 'ceramic' products sold in petrol stations. Here's how to tell them from the real thing, and why it matters.",
    readTime: "8 min",
  },
  {
    slug: "paint-correction-explained",
    title: "Paint Correction: What It Is, What It Isn't, and When You Need It",
    date: "2024-09-20",
    category: "Correction",
    excerpt: "Swirl marks, buffer trails, water etching — we break down the most common paint defects, what causes them, and how they're removed.",
    readTime: "10 min",
  },
  {
    slug: "washing-your-car-correctly",
    title: "The Two-Bucket Method Isn't Enough. Here's What We Actually Do.",
    date: "2024-07-08",
    category: "Maintenance",
    excerpt: "Most 'safe wash' advice online will still introduce swirl marks. This is our full maintenance wash protocol for paint-corrected and ceramic-coated cars.",
    readTime: "6 min",
  },
];
